# Edge Stream 配置文件

# 数据库配置
database:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: ENC(YWJjZGVmZ2hpams=)  # 加密的密码
    database: edge_stream
    charset: utf8mb4
    timeout: 30s
  
  postgresql:
    host: localhost
    port: 5432
    username: postgres
    password: ENC(cG9zdGdyZXNxbA==)  # 加密的密码
    database: edge_stream
    sslmode: disable
    timeout: 30s

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ENC(cmVkaXNwYXNz)  # 加密的密码
  db: 0
  timeout: 5s

# 服务器配置
server:
  host: localhost
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# 日志配置
logging:
  level: info
  format: json
  output: stdout

# 指标配置
metrics:
  enabled: true
  endpoint: /metrics
  interval: 30s

# 安全配置
security:
  encryption_key: ENC(bXlzZWNyZXRrZXk=)  # 加密的密钥
  jwt_secret: ENC(and0c2VjcmV0)  # 加密的JWT密钥
  tls_enabled: false
  cert_file: ""
  key_file: ""

# 处理器配置
processors:
  batch_size: 1000
  flush_interval: 10s
  max_retries: 3
  retry_delay: 1s

# 窗口管理器配置
window_manager:
  default_window_size: 60s
  max_windows: 100
  cleanup_interval: 300s