name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v -coverprofile=coverage.out ./...
    
    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html
    
    - name: Run tests with race detection
      run: go test -race -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly:"
          gofmt -s -l .
          exit 1
        fi
    
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
    - name: Run staticcheck
      run: staticcheck ./...
    
    - name: Run benchmarks
      run: go test -bench=. -benchmem ./internal/performance/
    
    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o bin/edge-stream-linux-amd64 ./examples/complete/
        GOOS=windows GOARCH=amd64 go build -o bin/edge-stream-windows-amd64.exe ./examples/complete/
        GOOS=darwin GOARCH=amd64 go build -o bin/edge-stream-darwin-amd64 ./examples/complete/
        GOOS=darwin GOARCH=arm64 go build -o bin/edge-stream-darwin-arm64 ./examples/complete/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: edge-stream-binaries
        path: bin/
    
    - name: Run security scan with gosec
      run: |
       go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec -fmt json -out gosec-report.json -stdout ./...
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-scan-results
        path: gosec-report.json