name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Run tests with coverage
      timeout-minutes: 20
      run: |
        go test -v -timeout=15m -coverprofile=coverage.out ./internal/...
        go tool cover -html=coverage.out -o coverage.html
    
    - name: Run tests with race detection
      timeout-minutes: 5
      run: |
        go test -race -v ./internal/metrics/
        go test -race -v ./internal/config/
    
    - name: Run benchmarks
      run: go test -bench=. -benchmem ./internal/performance/
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted properly:"
          gofmt -s -l .
          exit 1
        fi
    
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
    - name: Run staticcheck
      run: staticcheck ./...
    
    - name: Build
      run: go build -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Build for multiple platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o bin/edge-stream-linux-amd64 ./examples/complete/
        GOOS=windows GOARCH=amd64 go build -o bin/edge-stream-windows-amd64.exe ./examples/complete/
        GOOS=darwin GOARCH=amd64 go build -o bin/edge-stream-darwin-amd64 ./examples/complete/
        GOOS=darwin GOARCH=arm64 go build -o bin/edge-stream-darwin-arm64 ./examples/complete/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: edge-stream-binaries
        path: bin/